-- This file contains the aliases for the RAFE framework. It is used to simplify the import paths in the codebase.
-- Edit this to change the aliases in both the darklua and vscode config file.
return {
	["ui"] = "src/ui",
	["services"] = "src/services",
	["packages"] = "Packages",
	["server_packages"] = "ServerPackages",
	["classes"] = "src/classes",
	["modules"] = "src/modules",
	["server_modules"] = "src/server_modules"
}
