local fs = require("@lune/fs") :: any
local process = require("@lune/process") :: any
local task = require("@lune/task") :: any

print("Installing packages")

process.spawn("rokit", { "install" }, { stdio = "forward" })

print("Clearing old build")

if fs.isDir("./build") then
	fs.removeDir("./build")
end

print("Building darklua config")

process.spawn("lune", { "run", "scripts/darkluaconfig" }, { stdio = "forward" })

print("Building vscode aliases")

process.spawn("lune", { "run", "scripts/alias-builder" }, { stdio = "forward" })

print("Starting darklua watch")

-- get operating system, if mac then run dev.bash, otherwise run below line
if process.os == "macos" then
	task.spawn(process.spawn, "./dev.bash", {}, { stdio = "forward" })
else
	task.spawn(process.spawn, "./dev.bat", {}, { stdio = "forward" })
end

print("Starting server")

repeat
	task.wait()
until fs.isDir("./build") and fs.isDir("./build/services") and fs.isDir("./build/startup")

task.wait()

print("Starting rojo")

process.spawn("rojo", {
	"serve",
	"build.project.json",
}, { stdio = "forward" })